Feature: Create-Retrieve-Update-Delete
  In order to handle an entity
  As a client software developer
  I need to be able to handle an intervention entity through API Platform.

  Scenario: Create an intervention
    When I add "Content-Type" header equal to "application/ld+json"
    And I add "Accept" header equal to "application/ld+json"
    And I send a "POST" request to "/interventions" with body:
    """
    {
      "assetManager": "BF",
      "buildingCode": "BRUXELLE",
      "address": "Kleine Kloosterstart 10",
      "postCode": "1932",
      "city": "ZAVENTERN",
      "service": "078",
      "serviceDescription": "Recycling",
      "vendorContract": "VC000006",
      "vendor": "00000437",
      "vendorName": "SUEZ",
      "vendorAddress": "Lilsedijk 19",
      "vendorPostCode": "B-2340",
      "vendorCity": "BEERSE",
      "vendorCountryCode": "BE",
      "vendorContactName": "Gilberte Wynants",
      "vendorContactEmail": "n.grigorova@groupe-hli.com",
      "cgvAccepted": false
    }
    """
    Then the response status code should be 201
    And the response should be in JSON
    And the header "Content-Type" should be equal to "application/ld+json; charset=utf-8"
    And the header "Content-Location" should be equal to "/interventions/IRCO000058"
    And the header "Location" should be equal to "/interventions/IRCO000058"
    And the JSON should be equal to:
    """
    {
      "@context": "/contexts/Intervention",
      "@id": "/interventions/IRCO000058",
      "@type": "Intervention",
      "orderDate": "2020-03-30T00:00:00+00:00",
      "status": "Stand_By_Validation",
      "assetManager": "BF",
      "buildingCode": "BRUXELLE",
      "address": "Kleine Kloosterstart 10",
      "postCode": "1932",
      "city": "ZAVENTERN",
      "comment": null,
      "appointmentDate": "0001-01-01T00:00:00+00:00",
      "createdAt": "0001-01-01T00:00:00+00:00",
      "service": "078",
      "serviceDescription": "Recycling",
      "vendorContract": "VC000006",
      "vendor": "00000437",
      "vendorName": "SUEZ",
      "vendorAddress": "Lilsedijk 19",
      "vendorPostCode": "B-2340",
      "vendorCity": "BEERSE",
      "vendorCountryCode": "BE",
      "vendorContactName": "Gilberte Wynants",
      "vendorContactEmail": "n.grigorova@groupe-hli.com",
      "emailSentAt": "0001-01-01T00:00:00+00:00",
      "cgvAccepted": false
    }
    """

  Scenario: Get an intervention
    When I add "Accept" header equal to "application/ld+json"
    And I send a "GET" request to "/interventions/IRCO000029"
    Then the response status code should be 200
    And the response should be in JSON
    And the header "Content-Type" should be equal to "application/ld+json; charset=utf-8"
    And the JSON should be equal to:
    """
    {
      "@context": "/contexts/Intervention",
      "@id": "/interventions/IRCO000029",
      "@type": "Intervention",
      "orderDate": "2020-03-11T00:00:00+00:00",
      "status": "Email",
      "assetManager": "BF",
      "buildingCode": "BRUXELLE",
      "address": "Kleine Kloosterstart 10",
      "postCode": "1932",
      "city": "ZAVENTERN",
      "comment": "Test NavBundle",
      "appointmentDate": "0001-01-01T00:00:00+00:00",
      "createdAt": "0001-01-01T00:00:00+00:00",
      "service": "078",
      "serviceDescription": "Recycling",
      "vendorContract": "VC000006",
      "vendor": "00000437",
      "vendorName": "SUEZ",
      "vendorAddress": "Lilsedijk 19",
      "vendorPostCode": "B-2340",
      "vendorCity": "BEERSE",
      "vendorCountryCode": "BE",
      "vendorContactName": "Gilberte Wynants",
      "vendorContactEmail": "n.grigorova@groupe-hli.com",
      "emailSentAt": "2020-03-11T10:20:57+00:00",
      "cgvAccepted": false
    }
    """

  Scenario: Get a collection of Interventions
    When I add "Accept" header equal to "application/ld+json"
    And I send a "GET" request to "/interventions"
    Then the response status code should be 200
    And the response should be in JSON
    And the header "Content-Type" should be equal to "application/ld+json; charset=utf-8"
    And the JSON should be equal to:
    """
    {
      "@context": "/contexts/Intervention",
      "@id": "/interventions",
      "@type": "hydra:Collection",
      "hydra:member": [
        {
          "@id": "/interventions/IRCO000001",
          "@type": "Intervention",
          "orderDate": "2020-02-24T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "TB",
          "buildingCode": "VAL_PLAZ",
          "address": "Parc Tertiaire du Val d'Orson",
          "postCode": "35770",
          "city": "VERN SUR SEICHE",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-25T00:00:00+00:00",
          "service": "174",
          "serviceDescription": "Regulations – Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000002",
          "@type": "Intervention",
          "orderDate": "2020-02-24T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "2020-02-25T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-02-25T15:16:34+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000003",
          "@type": "Intervention",
          "orderDate": "2020-02-24T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "2020-02-25T00:00:00+00:00",
          "createdAt": "2020-02-24T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000004",
          "@type": "Intervention",
          "orderDate": "2020-02-25T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-25T00:00:00+00:00",
          "service": "041",
          "serviceDescription": "Utilities – Air conditioning",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000005",
          "@type": "Intervention",
          "orderDate": "2020-02-25T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:03:33+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000006",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "SB",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:03:42+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000007",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:03:51+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000008",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-28T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000009",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:04:15+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000010",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:04:39+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000011",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000012",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-28T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000013",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": "gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\njkjkjkjk\nnkjnjhkh\nj,k;jkjkj",
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-28T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000014",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-28T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000015",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-02-28T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000016",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:06:16+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000017",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:06:32+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000018",
          "@type": "Intervention",
          "orderDate": "2020-02-28T00:00:00+00:00",
          "status": "Closed",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000019",
          "@type": "Intervention",
          "orderDate": "2020-03-02T00:00:00+00:00",
          "status": "Requeste_quote_sent",
          "assetManager": "TB",
          "buildingCode": "DENAIN",
          "address": "Espace Villars",
          "postCode": "59220",
          "city": "DENAIN",
          "comment": "kjh",
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-03-02T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": "00001396",
          "vendorName": "BRUNET",
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": "FR",
          "vendorContactName": "Test Brunet 1",
          "vendorContactEmail": "pp.brunet1@test.fr",
          "emailSentAt": "2020-03-02T16:37:43+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000020",
          "@type": "Intervention",
          "orderDate": "2020-03-03T00:00:00+00:00",
          "status": "Stand_by_quote",
          "assetManager": "TB",
          "buildingCode": "DENAIN",
          "address": "Espace Villars",
          "postCode": "59220",
          "city": "DENAIN",
          "comment": "sdqfdsf",
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "011",
          "serviceDescription": "Lift",
          "vendorContract": null,
          "vendor": null,
          "vendorName": null,
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": null,
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000021",
          "@type": "Intervention",
          "orderDate": "2020-03-05T00:00:00+00:00",
          "status": "Email",
          "assetManager": "BF",
          "buildingCode": "DENAIN",
          "address": "Espace Villars",
          "postCode": "59220",
          "city": "DENAIN",
          "comment": "dsfqdsf",
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-03-05T00:00:00+00:00",
          "service": "172",
          "serviceDescription": "Regulations – Fire safety",
          "vendorContract": null,
          "vendor": "00001396",
          "vendorName": "BRUNET",
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": "FR",
          "vendorContactName": "Test Brunet 1",
          "vendorContactEmail": "pp.brunet1@test.fr",
          "emailSentAt": "2020-03-05T10:59:14+00:00",
          "cgvAccepted": true
        },
        {
          "@id": "/interventions/IRCO000022",
          "@type": "Intervention",
          "orderDate": "2020-03-05T00:00:00+00:00",
          "status": "Email",
          "assetManager": "BF",
          "buildingCode": "DENAIN",
          "address": "Espace Villars",
          "postCode": "59220",
          "city": "DENAIN",
          "comment": "sdfd",
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-03-05T00:00:00+00:00",
          "service": "171",
          "serviceDescription": "Regulations – Environmental",
          "vendorContract": null,
          "vendor": "00001396",
          "vendorName": "BRUNET",
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": "FR",
          "vendorContactName": "Test Brunet 1",
          "vendorContactEmail": "pp.brunet1@test.fr",
          "emailSentAt": "2020-03-05T12:55:01+00:00",
          "cgvAccepted": true
        },
        {
          "@id": "/interventions/IRCO000023",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Stand_By_Validation",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000024",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Stand_By_Validation",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000025",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Email",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000026",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Stand_by_quote",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": null,
          "vendorContactEmail": null,
          "emailSentAt": "0001-01-01T00:00:00+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000027",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Requeste_quote_sent",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-03-11T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:02:29+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000028",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Email",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "italie",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00001396",
          "vendorName": "BRUNET",
          "vendorAddress": null,
          "vendorPostCode": null,
          "vendorCity": "ZWOLLE",
          "vendorCountryCode": "FR",
          "vendorContactName": "Test Brunet 1",
          "vendorContactEmail": "pp.brunet1@test.fr",
          "emailSentAt": "2020-03-11T10:13:20+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000029",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Email",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "0001-01-01T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:20:57+00:00",
          "cgvAccepted": false
        },
        {
          "@id": "/interventions/IRCO000030",
          "@type": "Intervention",
          "orderDate": "2020-03-11T00:00:00+00:00",
          "status": "Requeste_quote_sent",
          "assetManager": "BF",
          "buildingCode": "BRUXELLE",
          "address": "Kleine Kloosterstart 10",
          "postCode": "1932",
          "city": "ZAVENTERN",
          "comment": null,
          "appointmentDate": "0001-01-01T00:00:00+00:00",
          "createdAt": "2020-03-11T00:00:00+00:00",
          "service": "078",
          "serviceDescription": "Recycling",
          "vendorContract": "VC000006",
          "vendor": "00000437",
          "vendorName": "SUEZ",
          "vendorAddress": "Lilsedijk 19",
          "vendorPostCode": "B-2340",
          "vendorCity": "BEERSE",
          "vendorCountryCode": "BE",
          "vendorContactName": "Gilberte Wynants",
          "vendorContactEmail": "n.grigorova@groupe-hli.com",
          "emailSentAt": "2020-03-11T10:23:50+00:00",
          "cgvAccepted": false
        }
      ],
      "hydra:totalItems": 30,
      "hydra:search": {
        "@type": "hydra:IriTemplate",
        "hydra:template": "/interventions{?no,no[],key,key[],orderDate,orderDate[],status,status[],assetManager,assetManager[],buildingCode,buildingCode[],address,address[],postCode,postCode[],city,city[],comment,comment[],appointmentDate,appointmentDate[],createdAt,createdAt[],service,service[],serviceDescription,serviceDescription[],vendorContract,vendorContract[],vendor,vendor[],vendorName,vendorName[],vendorAddress,vendorAddress[],vendorPostCode,vendorPostCode[],vendorCity,vendorCity[],vendorCountryCode,vendorCountryCode[],vendorContactName,vendorContactName[],vendorContactEmail,vendorContactEmail[],emailSentAt,emailSentAt[],cgvAccepted,cgvAccepted[]}",
        "hydra:variableRepresentation": "BasicRepresentation",
        "hydra:mapping": [
          {
            "@type": "IriTemplateMapping",
            "variable": "no",
            "property": "no",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "no[]",
            "property": "no",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "key",
            "property": "key",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "key[]",
            "property": "key",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "orderDate",
            "property": "orderDate",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "orderDate[]",
            "property": "orderDate",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "status",
            "property": "status",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "status[]",
            "property": "status",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "assetManager",
            "property": "assetManager",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "assetManager[]",
            "property": "assetManager",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "buildingCode",
            "property": "buildingCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "buildingCode[]",
            "property": "buildingCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "address",
            "property": "address",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "address[]",
            "property": "address",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "postCode",
            "property": "postCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "postCode[]",
            "property": "postCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "city",
            "property": "city",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "city[]",
            "property": "city",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "comment",
            "property": "comment",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "comment[]",
            "property": "comment",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "appointmentDate",
            "property": "appointmentDate",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "appointmentDate[]",
            "property": "appointmentDate",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "createdAt",
            "property": "createdAt",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "createdAt[]",
            "property": "createdAt",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "service",
            "property": "service",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "service[]",
            "property": "service",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "serviceDescription",
            "property": "serviceDescription",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "serviceDescription[]",
            "property": "serviceDescription",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContract",
            "property": "vendorContract",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContract[]",
            "property": "vendorContract",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendor",
            "property": "vendor",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendor[]",
            "property": "vendor",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorName",
            "property": "vendorName",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorName[]",
            "property": "vendorName",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorAddress",
            "property": "vendorAddress",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorAddress[]",
            "property": "vendorAddress",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorPostCode",
            "property": "vendorPostCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorPostCode[]",
            "property": "vendorPostCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorCity",
            "property": "vendorCity",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorCity[]",
            "property": "vendorCity",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorCountryCode",
            "property": "vendorCountryCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorCountryCode[]",
            "property": "vendorCountryCode",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContactName",
            "property": "vendorContactName",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContactName[]",
            "property": "vendorContactName",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContactEmail",
            "property": "vendorContactEmail",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "vendorContactEmail[]",
            "property": "vendorContactEmail",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "emailSentAt",
            "property": "emailSentAt",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "emailSentAt[]",
            "property": "emailSentAt",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "cgvAccepted",
            "property": "cgvAccepted",
            "required": false
          },
          {
            "@type": "IriTemplateMapping",
            "variable": "cgvAccepted[]",
            "property": "cgvAccepted",
            "required": false
          }
        ]
      }
    }
    """

  Scenario: Update an intervention
    When I add "Content-Type" header equal to "application/ld+json"
    And I add "Accept" header equal to "application/ld+json"
    And I send a "PUT" request to "/interventions/IRCO000029" with body:
    """
    {
      "@id": "/interventions/IRCO000029",
      "comment": "Test NavBundle"
    }
    """
    Then the response status code should be 200
    And the response should be in JSON
    And the header "Content-Type" should be equal to "application/ld+json; charset=utf-8"
    And the header "Content-Location" should be equal to "/interventions/IRCO000029"
    And the JSON should be equal to:
    """
    {
      "@context": "/contexts/Intervention",
      "@id": "/interventions/IRCO000029",
      "@type": "Intervention",
      "orderDate": "2020-03-11T00:00:00+00:00",
      "status": "Email",
      "assetManager": "BF",
      "buildingCode": "BRUXELLE",
      "address": "Kleine Kloosterstart 10",
      "postCode": "1932",
      "city": "ZAVENTERN",
      "comment": "Test NavBundle",
      "appointmentDate": "0001-01-01T00:00:00+00:00",
      "createdAt": "0001-01-01T00:00:00+00:00",
      "service": "078",
      "serviceDescription": "Recycling",
      "vendorContract": "VC000006",
      "vendor": "00000437",
      "vendorName": "SUEZ",
      "vendorAddress": "Lilsedijk 19",
      "vendorPostCode": "B-2340",
      "vendorCity": "BEERSE",
      "vendorCountryCode": "BE",
      "vendorContactName": "Gilberte Wynants",
      "vendorContactEmail": "n.grigorova@groupe-hli.com",
      "emailSentAt": "2020-03-11T10:20:57+00:00",
      "cgvAccepted": false
    }
    """

  Scenario: I cannot delete an intervention
    When I add "Accept" header equal to "application/ld+json"
    And I send a "DELETE" request to "/interventions/IRCO000058"
    Then the response status code should be 405
